name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --force
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Python setup
      if: always()
      uses: actions/setup-python@v3
      with:
          python-version: '3.x'
    - name: TestRail CLI upload results
      if: always()
      run: |
          pip install trcli
          trcli -y \
            -h https://orhan101.testrail.io/ \
            --project "Ui Tests" \
            -u demirci.orhan101@gmail.com \
            -p Miy.wGW8zuRYpClHCkKo \
            parse_junit \
            --title "Automated Tests from GitHub workflow" \
            --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -f "results.xml"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
