name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --force
    - name: Install Allure Command Line
      run: npm install -g allure-commandline --force
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm test
      
    - name: Generate allure Report
      if: always()
      run: allure generate allure-results -o allure-report --clean
      
#     - name: Send test results to Slack
#       if: always()
#       run: node tests/slack.js
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
    # This data can be any valid JSON from a previous step in the GitHub Action
         payload: |
           {
            "key": "value",
            "foo": "bar"
           }
  env:
    SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"


      
#     - name: Open allure Report
#       if: always()
#       run: allure open allure-report
      
#     - name: Python setup
#       if: always()
#       uses: actions/setup-python@v4
#       with:
#           python-version: '3.10'
#     - name: Update pip
#       if: always()
#       run: pip install --upgrade pip
#     - name: Send Test Report to Slack
#       if: always()
#       run: npm run slack
 
#     - name: TestRail CLI upload results
#       if: always()
#       run: |
#           pip install trcli
#           trcli -y \
#             -h https://orhan101.testrail.io/ \
#             --project "Practice" \
#             -u demirci.orhan101@gmail.com \
#             -p Miy.wGW8zuRYpClHCkKo \
#             parse_junit \
#             --title "Automated Tests from GitHub workflow" \
#             -f "results.xml"
#     - uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
   - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    - name: Setup Pages
      uses: actions/configure-pages@v2
      if: always()
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.7
      if: always()
      with:
          path: allure-report/
    - name: Deploy Playwright result to Github Pages
      id: deployment
      uses: actions/deploy-pages@v1.2.4
      if: always()
#     - name: Get Allure history
#       uses: actions/checkout@v2
#       if: always()
#       continue-on-error: true
#       with:
#           ref: gh-pages
#           path: gh-pages

#     - name: Allure Report action from marketplace
#       uses: simple-elf/allure-report-action@master
#       if: always()
#       id: allure-report
#       with:
#           allure_results: allure-results
#           gh_pages: gh-pages
#           allure_report: allure-report
#           allure_history: allure-history

#     - name: Deploy report to Github Pages
#       if: always()
#       uses: peaceiris/actions-gh-pages@v2
#       env:
#           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PUBLISH_BRANCH: gh-pages
#           PUBLISH_DIR: allure-history
