name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --force
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm test
    - name: Python setup
      if: always()
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - name: Update pip
      if: always()
      run: pip install --upgrade pip
    - name: Send Test Report to Slack
      if: always()
      run: npm run slack
 
#     - name: TestRail CLI upload results
#       if: always()
#       run: |
#           pip install trcli
#           trcli -y \
#             -h https://orhan101.testrail.io/ \
#             --project "Practice" \
#             -u demirci.orhan101@gmail.com \
#             -p Miy.wGW8zuRYpClHCkKo \
#             parse_junit \
#             --title "Automated Tests from GitHub workflow" \
#             -f "results.xml"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
